name: PROD (api)

on:
  push:
    branches:
      - master
    paths:
      - "src/api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/khoj-api
          tags: "stable"
          workdir: src/api/
