name: PROD (ui-web-team)

on:
  push:
    branches:
      - master
    paths:
      - "src/ui-web-team/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/khoj-ui-web-team
          tags: "stable"
          workdir: src/ui-web-team/
