name: STAGING (api)

on:
  push:
    branches:
      - development
    paths:
      - "src/api/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo 'hi'
