name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      ui-web-community: ${{ steps.filter.outputs.ui-web-community }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            api:
                - 'src/api/**/*'
            ui-web-community:
                - 'src/ui-web-community/**/*'

  api:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/khoj-api
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: src/api/

  ui-web-community:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.output.ui-web-community }}
    steps:
      - name: Run a one-line script
        run: echo Deploying UI Web Community
