name: PROD (ui-web-team)

on:
  push:
    branches:
      - development
    paths:
      - "src/ui-web-team/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo 'hi'
