name: Deploy to Staging

on:
  push:
    branches:
      - development

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      ui-web-community: ${{ steps.filter.outputs.ui-web-community }}
    steps:
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            api:
                - 'src/api/**/*'
            ui-web-community:
                - 'src/ui-web-community/**/*'

  api:
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    steps:
      - name: Run a one-line script
        run: echo Deploying API

  ui-web-community:
    needs: changes
    if: ${{ needs.changes.output.ui-web-community }}
    steps:
      - name: Run a one-line script
        run: echo Deploying UI Web Community
