name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api }}
      uiwebcommunity: ${{ steps.filter.outputs.uiwebcommunity }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            api:
                - 'src/api-2/**/*'
            uiwebcommunity:
                - 'src/ui-web-community/**/*'

  api:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Publish to Docker
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/khoj-api
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: src/api-2/

      - name: Deploy to k8s
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.K8S_HOST_PROD }}
          username: ${{ secrets.K8S_USERNAME }}
          key: ${{ secrets.K8S_KEY }}
          script: |
            ./autodeploy_khoj_rest.sh ${{ steps.vars.outputs.sha_short }} >> ~/deploy.log 2>&1

      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed Khoj to staging environment"
          SLACK_TITLE: "staging-deploy workflow complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg

  ui-web-community:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.output.uiwebcommunity == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      - name: Install Packages
        run: npm install

      - name: Build Site
        run: npm run build
      - name: Deploy Site
        run: npm run deploy

      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deployed Khoj Community UI to production environment"
          SLACK_TITLE: "deploy-production workflow complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg
